version: "3.9"

services:

  server:
    container_name: codeninjas-server
    build: .
    ports:
      - 6000:6000
    restart: always
    environment:
      MONGODB_USERNAME=${MONGODB_USERNAME}
      MONGODB_PASSWORD=${MONGODB_PASSWORD}

